version: "3.6"

services:
  jupyter:
    image: jupyter/tensorflow-notebook:latest
    container_name: jupyter
    volumes:
      - jupyter_data:/home/jovyan/work
    restart: unless-stopped
    networks:
      - traefik
    labels:
      my.zone: dirtybit
      traefik.enable: true
      traefik.http.routers.jupyter.rule: Host(`${SUBDOMAIN:-jupyter}.${DOMAIN}`)
      traefik.http.routers.jupyter.entrypoints: websecure
      traefik.http.services.jupyter.loadbalancer.server.port: 8888

volumes:
  jupyter_data:

networks:
  traefik:
    name: dirtybit
    external: true
