version: "3.6"

services:
  tubearchivist:
    container_name: tube-archivist
    restart: unless-stopped
    image: bbilly1/tubearchivist
    volumes:
      - $MEDIA_PATH:/youtube
      - cache:/cache
    environment:
      - ES_URL=http://archivist-es:9200              # needs protocol e.g. http and port
      - REDIS_HOST=archivist-redis                   # don't add protocol
      - TA_HOST=${SUBDOMAIN:-tube}.${DOMAIN}         # set your host name
    depends_on:
      - archivist-es
      - archivist-redis
    networks:
      - traefik
    labels:
      my.zone: dirtybit
      traefik.enable: true
      traefik.http.routers.tubearchivist.rule: Host(`${SUBDOMAIN:-tube}.${DOMAIN}`)
      traefik.http.routers.tubearchivist.entrypoints: websecure
      traefik.http.services.tubearchivist.loadbalancer.server.port: 8000
  archivist-redis:
    image: redislabs/rejson                 # for arm64 use bbilly1/rejson
    container_name: archivist-redis
    restart: unless-stopped
    expose:
      - "6379"
    volumes:
      - redis:/data
    depends_on:
      - archivist-es
  archivist-es:
    image: bbilly1/tubearchivist-es         # only for amd64, or use official es 8.4.3
    container_name: archivist-es
    restart: unless-stopped
    environment:
      - "ELASTIC_PASSWORD=$ELASTIC_PASSWORD"       # matching Elasticsearch password
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "xpack.security.enabled=true"
      - "discovery.type=single-node"
      - "path.repo=/usr/share/elasticsearch/data/snapshot"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es:/usr/share/elasticsearch/data    # check for permission error when using bind mount, see readme
    expose:
      - "9200"

volumes:
  cache:
  redis:
  es:

networks:
  traefik:
    name: dirtybit