version: "3.6"
services:
  pihole:
    container_name: ebnf-viewer
    image: ghcr.io/dirtybit/enbf-viewer:latest
    restart: unless-stopped
    networks:
      - traefik
    labels:
      my.zone: dirtybit
      traefik.enable: true
      traefik.http.routers.ebnfviewer.rule: Host(`${SUBDOMAIN:-ebnf}.${DOMAIN}`)
      traefik.http.routers.ebnfviewer.entrypoints: websecure
      traefik.http.services.ebnfviewer.loadbalancer.server.port: 80

networks:
  traefik:
    name: dirtybit
